name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run ESLint
        run: bun run lint

  typecheck:
    runs-on: ubuntu-24.04-arm
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - name: Type-check with tsc
        run: bun run typecheck

  test:
    runs-on: ubuntu-24.04-arm
    needs: [lint, typecheck]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - name: Run unit tests
        run: bun run test

  build:
    runs-on: ubuntu-24.04-arm
    needs: test
    strategy:
      matrix:
        mode: [chrome, firefox, development]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install

      - name: Build (${{ matrix.mode }})
        run: |
          if [ "${{ matrix.mode }}" = "chrome" ]; then
            bunx vite build --mode chrome
          elif [ "${{ matrix.mode }}" = "firefox" ]; then
            bunx vite build --mode firefox
          else
            bunx vite build --mode development
          fi

      - name: Upload ${{ matrix.mode }}-build
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.mode }}-build
          path: ${{ matrix.mode == 'development' && 'dist' || github.workspace }}/${{ matrix.mode == 'firefox' && 'firefox-extension.zip' || 'chrome-extension.zip' }}
